# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/85f6b7c2-5e8e-4e56-9a90-1a6d4a1e14f5";
    fsType = "btrfs";
    options = [ "subvol=@root" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4271-BB35";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/85f6b7c2-5e8e-4e56-9a90-1a6d4a1e14f5";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/mnt/unified" = {
    device = "/dev/disk/by-uuid/85f6b7c2-5e8e-4e56-9a90-1a6d4a1e14f5";
    fsType = "btrfs";
    options = [ "subvol=@unified" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/900a7002-5b2c-47ab-a734-c4e44c32f7f4"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
